title: "Suhyun’s Research Notes on AI in Medical Informatics"
description: "Research notes on clinical NLP, AI-based analysis of medical data, and drug discovery"
author: "Suhyun An (Julie)"
theme: minima
